Repository Telecominfraproject/oopt-gnpy, pull requests merged in 2019-09, with the labels that each got.

#289 Raman: linear interpolation of channel NLI
  examples/transmission_main_example.py
  gnpy/core/science_utils.py
Labels: bug

#292 Fix per-channel SNR output
  examples/transmission_main_example.py
Labels: enhancement

#249 Do not mix THz and Hz
  gnpy/core/elements.py
Labels: bug

#295 Automatic building of Docker images
  .docker-entry.sh
  .docker-travis.sh
  .travis.yml
  Dockerfile
Labels: enhancement

#296 Travis: Docker: Fix version numbers
  .travis.yml
Labels: enhancement

#300 docs: Document Transceiver.mode.OSNR
  json_structure_description.rst
Labels: bug, documentation

#299 Refactor printing
  examples/path_requests_run.py
  examples/transmission_main_example.py
  gnpy/core/ansi_escapes.py
  gnpy/core/request.py
  tests/test_automaticmodefeature.py
Labels: bug, enhancement

#301 docs: Explain how to use Docker
  README.rst
Labels: documentation

#306 docs: show a DOI
  README.rst
Labels: documentation
